# docker-compose --env-file=.env.local up

version: "3.9"
services:
  al-nginx:
    build:
      context: nginx
    image: al-nginx
    ports:
      - 80:80
      - 443:443
    restart: always
  al-mission-control:
    image: docker.pkg.github.com/opendata-mvcr/mission-control/al-mission-control:latest
    environment:
      CONTEXT:
      ID: missionControl
      URL: ${URL}
      COMPONENTS:
    restart: always
  al-ontographer:
    image: docker.pkg.github.com/opendata-mvcr/ontographer/al-ontographer:latest
    environment:
      CONTEXT:
      ID: ontographer
      URL: ${URL}/v-nástroji/ontographer
      COMPONENTS:
    restart: always
  al-termit:
    image: docker.pkg.github.com/opendata-mvcr/termit-ui/al-termit:latest
    environment:
      CONTEXT:
      ID: termit
      URL: ${URL}/v-nástroji/termit
      COMPONENTS:
  al-db-server:
    build:
      context: al-db-server
      args:
        GRAPHDB_ZIP: graphdb-free-9.6.0-dist.zip
    image: al-graphdb
    environment:
      CONTEXT:
      ID: al-db-server
      URL: ${URL}/sluzby/al-db-server/repositories/assembly-line
      COMPONENTS: # TODO REPOSITORY_USERNAME and REPOSITORY_PASSWORD
      GDB_JAVA_OPTS: >-
        -Dgraphdb.workbench.external-url=${URL}/sluzby/al-db-server
        -Dgraphdb.external-url=${URL}/sluzby/al-db-server
      GRAPHDB_WORKBENCH_EXTERNAL_URL: ${URL}/sluzby/al-db-server
      GRAPHDB_EXTERNAL_URL: ${URL}/sluzby/al-db-server
    restart: always
    volumes:
      - al-graphdb:/graphdb/home
  keycloakPostgres:
    image: postgres
    environment:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    restart: always
    volumes:
      - al-keycloak-postgres:/var/lib/postgresql/data
  al-auth-server:
    image: docker.pkg.github.com/opendata-mvcr/keycloak-graphdb-user-replicator/al-keycloak:latest
    environment:
      CONTEXT:
      ID: al-auth-server
      URL: ${URL}/sluzby/al-auth-server/realms/assembly-line
      COMPONENTS: # then REPOSITORY_USERNAME and REPOSITORY_PASSWORD
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloakPostgres
      DB_DATABASE: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_SCHEMA: public
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      REALM_ID: assembly-line
      KEYCLOAK_USER:
      KEYCLOAK_PASSWORD:
      PROXY_ADDRESS_FORWARDING: "true"
      KEYCLOAK_FRONTEND_URL: ${URL}/sluzby/al-auth-server
      KEYCLOAK_IMPORT: /al-auth-server/keycloak-realm.json
      DB_SERVER_URL: http://al-db-server:7200
      DB_SERVER_REPOSITORY_ID: assembly-line
      DB_SERVER_CONTEXT: https://slovník.gov.cz/uživatel
      NAMESPACE: https://slovník.gov.cz/uživatel/
    depends_on:
      - keycloakPostgres
      - al-db-server
    restart: always
    volumes:
      - al-keycloak:/keycloak
      - /etc/ssl/private/tls.key:/etc/x509/https/tls.key
      - /etc/ssl/certs/tls.crt:/etc/x509/https/tls.crt
      - ./al-auth-server:/al-auth-server
  al-sgov-server:
    image: docker.pkg.github.com/opendata-mvcr/sgov/al-sgov:latest
    environment:
      CONTEXT:
      ID: al-sgov-server
      URL: ${URL}/sluzby/al-sgov-server
      COMPONENTS:
      REPOSITORY_URL: http://al-db-server:7200/repositories/assembly-line
      KEYCLOAK_REALM: assembly-line
      KEYCLOAK_RESOURCE: al-sgov-server
      KEYCLOAK_AUTHSERVERURL: http://al-auth-server:8080/modelujeme/sluzby/al-auth-server
      KEYCLOAK_REALMKEY: ${KEYCLOAK_REALMKEY}
      KEYCLOAK_CREDENTIALS_SECRET: ${SGOV_SERVER_KEYCLOAK_CREDENTIALS_SECRET}
      KEYCLOAK_PUBLIC_CLIENT: "false"
      REPOSITORY_GITHUBUSERTOKEN: ${SGOV_SERVER_REPOSITORY_GITHUBUSERTOKEN}
      USER_NAMESPACE: https://slovník.gov.cz/uživatel/
      USER_CONTEXT: https://slovník.gov.cz/uživatel
    depends_on:
      - al-db-server
      - al-auth-server
    restart: always
  al-termit-server:
    image: docker.pkg.github.com/opendata-mvcr/termit/al-termit:latest
    environment:
      CONTEXT:
      ID: al-termit-server
      URL: ${URL}/sluzby/al-termit-server
      COMPONENTS:
      CORS_ALLOWEDORIGIN: "*"
      CANONICAL_CACHE_CONTAINER: https://slovník.gov.cz
      SERVER_SERVLET_CONTEXT-PATH: /modelujeme/sluzby/al-termit-server
      REPOSITORY_URL: http://al-db-server:7200/repositories/assembly-line
      KEYCLOAK_REALM: assembly-line
      KEYCLOAK_RESOURCE: al-termit-server
      KEYCLOAK_AUTHSERVERURL: http://al-auth-server:8080/modelujeme/sluzby/al-auth-server
      KEYCLOAK_REALMKEY: ${KEYCLOAK_REALMKEY}
      KEYCLOAK_CREDENTIALS_SECRET: ${TERMIT_SERVER_KEYCLOAK_CREDENTIALS_SECRET}
      KEYCLOAK_PUBLIC_CLIENT: "false"
      NAMESPACE_USER: https://slovník.gov.cz/uživatel/
    depends_on:
      - al-db-server
      - al-auth-server
    restart: always
    volumes:
      - al-termit:/tmp/termit

volumes:
  al-graphdb:
  al-keycloak-postgres:
  al-keycloak:
  al-termit:
