# docker-compose --env-file=.env.local up

version: "3.9"
services:
  nginx:
    build:
      context: nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
  mission-control:
    image: docker.pkg.github.com/opendata-mvcr/mission-control/mission-control:latest
    environment:
      - CONTEXT
      - ID=kodi-mission-control-dev # TODO: change to missionControl after Kaycloak is fixed
      - URL=${URL}/modelujeme
      - COMPONENTS
