# docker-compose --env-file=.env.local up

version: "3.9"
services:
  al-nginx:
    image: nginx:latest
    volumes:
      - ./al-nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./al-nginx/error.html:/usr/share/nginx/html/error.html
    ports:
      - 1234:80
    restart: always
    depends_on:
      - al-mission-control
      - al-termit
      - al-ontographer
      - al-db-server
      - al-auth-server
      - al-sgov-server
      - al-termit-server
  al-mission-control:
    image: docker.pkg.github.com/opendata-mvcr/mission-control/al-mission-control:latest
    environment:
      CONTEXT:
      ID: al-mission-control
      URL: ${URL}
      COMPONENTS:
    restart: always
  al-ontographer:
    image: docker.pkg.github.com/opendata-mvcr/ontographer/al-ontographer:latest
    environment:
      CONTEXT:
      ID: al-ontographer
      URL: ${URL}/v-nástroji/ontographer
      COMPONENTS:
    restart: always
  al-termit:
    image: docker.pkg.github.com/opendata-mvcr/termit-ui/al-termit:latest
    environment:
      CONTEXT:
      ID: al-termit
      URL: ${URL}/v-nástroji/termit
      COMPONENTS:
    restart: always
  al-db-server:
    build:
      context: al-db-server
      args:
        GRAPHDB_ZIP: graphdb-free-9.6.0-dist.zip
    image: al-graphdb
    environment:
      CONTEXT:
      ID: al-db-server
      URL: ${URL}/sluzby/db-server/repositories/assembly-line
      COMPONENTS: # TODO REPOSITORY_USERNAME and REPOSITORY_PASSWORD
      GDB_JAVA_OPTS: >-
        -Dgraphdb.workbench.external-url=${URL}/sluzby/db-server
        -Dgraphdb.external-url=${URL}/sluzby/db-server
        -Dgraphdb.workbench.cors.enable=true
        -Dgraphdb.connector.maxHttpHeaderSize=65536
      GRAPHDB_WORKBENCH_EXTERNAL_URL: ${URL}/sluzby/db-server
      GRAPHDB_EXTERNAL_URL: ${URL}/sluzby/db-server
    restart: always
    volumes:
      - al-db-server:/graphdb/home
  al-auth-server-db:
    image: postgres
    environment:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    restart: always
    volumes:
      - al-auth-server-db:/var/lib/postgresql/data
  al-auth-server:
    image: docker.pkg.github.com/opendata-mvcr/keycloak-graphdb-user-replicator/al-auth-server:latest
    environment:
      CONTEXT:
      ID: al-auth-server
      URL: ${URL}/sluzby/auth-server/realms/assembly-line
      COMPONENTS: # then REPOSITORY_USERNAME and REPOSITORY_PASSWORD
      DB_VENDOR: POSTGRES
      DB_ADDR: al-auth-server-db
      DB_DATABASE: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_SCHEMA: public
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      REALM_ID: assembly-line
      KEYCLOAK_USER:
      KEYCLOAK_PASSWORD:
      PROXY_ADDRESS_FORWARDING: "true"
      KEYCLOAK_FRONTEND_URL: ${URL}/sluzby/auth-server
      KEYCLOAK_IMPORT: /al-auth-server/keycloak-realm.json
      DB_SERVER_URL: http://al-db-server:7200
      DB_SERVER_REPOSITORY_ID: assembly-line
      DB_SERVER_CONTEXT: https://slovník.gov.cz/uživatel
      NAMESPACE: https://slovník.gov.cz/uživatel/
    depends_on:
      - al-auth-server-db
      - al-db-server
    restart: always
    volumes:
      - ./al-auth-server:/al-auth-server
  al-sgov-server:
    image: docker.pkg.github.com/opendata-mvcr/sgov/al-sgov-server:latest
    environment:
      CONTEXT:
      ID: al-sgov-server
      URL: ${URL}/sluzby/sgov-server
      COMPONENTS:
      SERVER_SERVLET_CONTEXT-PATH: /modelujeme/sluzby/sgov-server
      REPOSITORY_URL: http://al-db-server:7200/repositories/assembly-line
      KEYCLOAK_REALM: assembly-line
      KEYCLOAK_RESOURCE: al-sgov-server
      KEYCLOAK_AUTHSERVERURL: http://al-auth-server:8080/modelujeme/sluzby/auth-server
      KEYCLOAK_REALMKEY: ${KEYCLOAK_REALMKEY}
      KEYCLOAK_CREDENTIALS_SECRET: ${SGOV_SERVER_KEYCLOAK_CREDENTIALS_SECRET}
      KEYCLOAK_PUBLIC_CLIENT: "false"
      REPOSITORY_GITHUBUSERTOKEN: ${SGOV_SERVER_REPOSITORY_GITHUBUSERTOKEN}
      USER_NAMESPACE: https://slovník.gov.cz/uživatel/
      USER_CONTEXT: https://slovník.gov.cz/uživatel
      FEATURE_DEMO: ${FEATURE_DEMO:-false}
    depends_on:
      - al-db-server
      - al-auth-server
    restart: always
  al-termit-server:
    image: docker.pkg.github.com/opendata-mvcr/termit/al-termit-server:latest
    environment:
      CONTEXT:
      ID: al-termit-server
      URL: ${URL}/sluzby/termit-server
      COMPONENTS:
      TERMIT_CORS_ALLOWEDORIGIN: "*"
      TERMIT_REPOSITORY_CANONICAL_CONTAINER: https://slovník.gov.cz
      TERMIT_REPOSITORY_URL: http://al-db-server:7200/repositories/assembly-line
      TERMIT_REPOSITORY_PUBLICURL: ${URL}/sluzby/db-server/repositories/assembly-line
      TERMIT_TEXTANALYSIS_URL: http://al-annotace-server:8080/annotate?enableKeywordExtraction=true
      TERMIT_TEXTANALYSIS_TERMOCCURRENCEMINSCORE: "0.49"
      TERMIT_TEXTANALYSIS_TERMASSIGNMENTMINSCORE: "1"
      TERMIT_NAMESPACE_USER: https://slovník.gov.cz/uživatel/
      SERVER_SERVLET_CONTEXT-PATH: /modelujeme/sluzby/termit-server
      KEYCLOAK_REALM: assembly-line
      KEYCLOAK_RESOURCE: al-termit-server
      KEYCLOAK_AUTHSERVERURL: http://al-auth-server:8080/modelujeme/sluzby/auth-server
      KEYCLOAK_REALMKEY: ${KEYCLOAK_REALMKEY}
      KEYCLOAK_CREDENTIALS_SECRET: ${TERMIT_SERVER_KEYCLOAK_CREDENTIALS_SECRET}
      KEYCLOAK_PUBLIC_CLIENT: "false"
    depends_on:
      - al-db-server
      - al-auth-server
    restart: always
    volumes:
      - al-termit-server:/tmp/termit
  al-annotace-server:
    image: ghcr.io/kbss-cvut/annotace/annotace-spark:latest
    environment:
      JAVA_OPTS: "-Xmx1g"
    ports:
      - "8888:8080"
    restart: always

volumes:
  al-db-server:
  al-auth-server-db:
  al-termit-server:
